(() => {
  'use strict';
  const $=id=>document.getElementById(id);
  const els={fileInput:$('fileInput'),uploadButton:$('uploadButton'),uploadError:$('uploadError'),workspace:$('workspace'),fileName:$('fileName'),originalPreview:$('originalPreview'),vectorPreview:$('vectorPreview'),compareOriginal:$('compareOriginal'),compareVector:$('compareVector'),comparePreview:$('comparePreview'),compareVectorClip:$('compareVectorClip'),compareSlider:$('compareSlider'),vectorizeButton:$('vectorizeButton'),colorCount:$('colorCount'),removeBackground:$('removeBackground'),detail:$('detail'),statusText:$('statusText'),useCases:$('useCases'),analysisPanel:$('analysisPanel'),analysisSummary:$('analysisSummary'),palettePreview:$('palettePreview'),printCheck:$('printCheck'),printStatus:$('printStatus'),printWarnings:$('printWarnings'),exports:$('exports'),downloadSvg:$('downloadSvg'),downloadPdf:$('downloadPdf'),downloadPng:$('downloadPng'),downloadAll:$('downloadAll'),saveProject:$('saveProject'),resetButton:$('resetButton'),accountButton:$('accountButton'),projectsButton:$('projectsButton'),creditBadge:$('creditBadge'),accountDialog:$('accountDialog'),authTitle:$('authTitle'),authEmail:$('authEmail'),authPassword:$('authPassword'),authError:$('authError'),authSubmit:$('authSubmit'),authToggle:$('authToggle'),logoutButton:$('logoutButton'),projectsDialog:$('projectsDialog'),projectsClose:$('projectsClose'),projectList:$('projectList')};
  const useCases=['T-shirt / apparel','Jersey / uniform','Hat / embroidery','Screen printing','Sign / banner','Vinyl / decal','Sticker','Packaging','Business printing','Web / digital','Just give me the vector'];
  let state={file:null,image:null,mode:'trace',useCase:useCases[0],result:null,svg:null,sourceUrl:null,user:null,authMode:'login',exportUnlocked:false,loadedProjectId:null,check:null};

  const api=async(url,options={})=>{const r=await fetch(url,{credentials:'same-origin',headers:{'Content-Type':'application/json',...(options.headers||{})},...options});if(r.status===204)return null;const data=await r.json().catch(()=>({}));if(!r.ok)throw Object.assign(new Error(data.error||'request_failed'),{status:r.status,data});return data;};
  const track=(event_name,metadata={})=>{fetch('/api/events',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({event_name,metadata}),keepalive:true}).catch(()=>{});};
  const escapeHtml=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

  function initUseCases(){els.useCases.innerHTML='';useCases.forEach((name,i)=>{const b=document.createElement('button');b.type='button';b.className='chip'+(i===0?' active':'');b.textContent=name;b.addEventListener('click',()=>{state.useCase=name;[...els.useCases.children].forEach(x=>x.classList.toggle('active',x===b));track('use_case_selected',{use_case:name});if(state.result)renderPrintCheck();});els.useCases.appendChild(b);});}
  function setView(view){document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.view===view));els.originalPreview.classList.toggle('hidden',view!=='original');els.vectorPreview.classList.toggle('hidden',view!=='vector');els.comparePreview.classList.toggle('hidden',view!=='compare');if(view==='compare'&&!state.svg)setView('original');}
  function validateFile(file){if(!file)return'Choose an image first.';const allowed=['image/png','image/jpeg','image/webp'];if(!allowed.includes(file.type))return'Please upload a PNG, JPG, or WEBP image.';if(file.size>20*1024*1024)return'This file is larger than the 20 MB limit.';return'';}
  function rasterize(maxDim=1100){const w=state.image.naturalWidth,h=state.image.naturalHeight,scale=Math.min(1,maxDim/Math.max(w,h)),cw=Math.max(1,Math.round(w*scale)),ch=Math.max(1,Math.round(h*scale));const canvas=document.createElement('canvas');canvas.width=cw;canvas.height=ch;const ctx=canvas.getContext('2d',{willReadFrequently:true});ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high';ctx.drawImage(state.image,0,0,cw,ch);return{canvas,ctx,imageData:ctx.getImageData(0,0,cw,ch)};}
  function analyzeImage(){const {imageData}=rasterize(420),q=VectorCore.quantize(imageData,8),palette=q.centers,bg=VectorCore.likelyBackground(imageData,q);let alpha=0;for(let i=3;i<imageData.data.length;i+=4)if(imageData.data[i]<245)alpha++;const transparent=alpha/(imageData.data.length/4)>.01;const colorSpread=palette.length;const type=colorSpread<=3?'Logo / flat graphic':colorSpread<=6?'Badge / illustration':'Complex artwork';els.analysisPanel.classList.remove('hidden');els.analysisSummary.innerHTML=`<div class="analysis-row"><span>Likely type</span><strong>${type}</strong></div><div class="analysis-row"><span>Source size</span><strong>${state.image.naturalWidth} × ${state.image.naturalHeight}</strong></div><div class="analysis-row"><span>Transparency</span><strong>${transparent?'Yes':'No'}</strong></div><div class="analysis-row"><span>Likely background</span><strong>${bg>=0?'Detected':'None'}</strong></div>`;els.palettePreview.innerHTML='';palette.forEach(c=>{const s=document.createElement('span');s.className='swatch';s.style.background=`rgb(${c.join(',')})`;s.title=`rgb(${c.join(', ')})`;els.palettePreview.appendChild(s);});const recommended=colorSpread<=3?2:colorSpread<=6?4:8;els.colorCount.value=String(recommended);track('analysis_completed',{type,recommended_colors:recommended});}
  function handleFile(file){const error=validateFile(file);els.uploadError.textContent=error;if(error){track('upload_failed',{reason:error});return;}if(state.sourceUrl)URL.revokeObjectURL(state.sourceUrl);state.file=file;state.sourceUrl=URL.createObjectURL(file);state.result=null;state.svg=null;state.loadedProjectId=null;state.exportUnlocked=false;const img=new Image();img.onload=()=>{if(img.naturalWidth<16||img.naturalHeight<16){els.uploadError.textContent='This image is too small to vectorize reliably.';return;}if(img.naturalWidth*img.naturalHeight>36_000_000){els.uploadError.textContent='This image has too many pixels. Resize it below 36 megapixels and try again.';return;}state.image=img;els.originalPreview.src=state.sourceUrl;els.compareOriginal.src=state.sourceUrl;els.fileName.textContent=file.name;els.workspace.classList.remove('hidden');els.printCheck.classList.add('hidden');els.exports.classList.add('hidden');els.vectorPreview.innerHTML='';els.compareVector.innerHTML='';setView('original');els.statusText.textContent=`${img.naturalWidth} × ${img.naturalHeight}px loaded. Choose settings and vectorize.`;analyzeImage();track('upload_completed',{mime:file.type,size:file.size,width:img.naturalWidth,height:img.naturalHeight});els.workspace.scrollIntoView({behavior:'smooth',block:'start'});};img.onerror=()=>{els.uploadError.textContent='The image could not be decoded. It may be corrupt or mislabeled.';track('upload_failed',{reason:'decode'});};img.src=state.sourceUrl;track('upload_started',{mime:file.type,size:file.size});}

  function vectorize(){if(!state.image)return;els.vectorizeButton.disabled=true;els.statusText.textContent='Analyzing colors, finding shapes, cleaning edges…';track('vectorization_started',{mode:state.mode,use_case:state.useCase});requestAnimationFrame(()=>setTimeout(()=>{try{const {imageData}=rasterize();state.result=VectorCore.vectorize(imageData,{colorCount:Number(els.colorCount.value),removeBackground:els.removeBackground.checked,detail:els.detail.value,mode:state.mode});if(!state.result.shapes.length)throw new Error('No vector shapes found');state.svg=VectorCore.resultToSvg(state.result);state.exportUnlocked=false;els.vectorPreview.innerHTML=state.svg;els.compareVector.innerHTML=state.svg;els.vectorPreview.classList.add('vector-preview');renderPrintCheck();els.exports.classList.remove('hidden');setView('vector');const nodes=state.result.shapes.reduce((n,s)=>n+s.points.length,0);els.statusText.textContent=`Created ${state.result.shapes.length} vector shapes with ${nodes.toLocaleString()} path nodes.`;track('vectorization_completed',{mode:state.mode,shapes:state.result.shapes.length,nodes});}catch(err){console.error(err);els.statusText.textContent='This image could not be vectorized with the current settings. Try fewer colors or lower detail.';track('vectorization_failed',{message:err.message});}finally{els.vectorizeButton.disabled=false;}},30));}
  function renderPrintCheck(){state.check=VectorCore.printCheck(state.result,state.useCase);els.printCheck.classList.remove('hidden');els.printStatus.textContent=state.check.status;els.printWarnings.innerHTML='';const warnings=state.check.warnings.length?state.check.warnings:['No major production issues detected. Your manufacturer may still have additional requirements.'];warnings.forEach(w=>{const li=document.createElement('li');li.textContent=w;els.printWarnings.appendChild(li);});track('print_check_completed',{status:state.check.status,warnings:state.check.warnings.length,use_case:state.useCase});}

  function basename(){return(state.file?.name||'artwork').replace(/\.[^.]+$/,'').replace(/[^a-z0-9_-]+/gi,'-').replace(/^-|-$/g,'')||'artwork';}
  function downloadBlob(blob,name){const a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1500);}
  async function pngBlob(){return await new Promise((resolve,reject)=>{const url=URL.createObjectURL(new Blob([state.svg],{type:'image/svg+xml'})),img=new Image();img.onload=()=>{const scale=Math.min(4,4096/Math.max(state.result.width,state.result.height)),c=document.createElement('canvas');c.width=Math.round(state.result.width*scale);c.height=Math.round(state.result.height*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);URL.revokeObjectURL(url);c.toBlob(b=>b?resolve(b):reject(new Error('png_failed')),'image/png');};img.onerror=reject;img.src=url;});}
  async function authorizeExport(){if(state.exportUnlocked)return true;const freeKey='vm_free_project_export_used';if(localStorage.getItem(freeKey)!=='1'){localStorage.setItem(freeKey,'1');state.exportUnlocked=true;track('free_export_unlocked');return true;}if(!state.user){els.authError.textContent='Your free export has been used. Sign in to use purchased export credits.';openAuth();return false;}try{const data=await api('/api/exports/consume',{method:'POST',body:'{}'});state.user=data.user;renderUser();state.exportUnlocked=true;track('credit_export_unlocked');return true;}catch(e){if(e.status===402){document.getElementById('pricing').scrollIntoView({behavior:'smooth'});alert('You need an export credit. Choose a pack below.');return false;}throw e;}}
  async function downloadSvg(){if(state.svg&&await authorizeExport()){downloadBlob(new Blob([state.svg],{type:'image/svg+xml;charset=utf-8'}),`${basename()}-vector.svg`);track('download_svg');}}
  async function downloadPdf(){if(state.result&&await authorizeExport()){downloadBlob(VectorCore.resultToPdf(state.result),`${basename()}-vector.pdf`);track('download_pdf');}}
  async function downloadPng(){if(state.result&&await authorizeExport()){downloadBlob(await pngBlob(),`${basename()}-transparent.png`);track('download_png');}}
  async function downloadAll(){if(!state.result||!await authorizeExport())return;const pdf=VectorCore.resultToPdf(state.result),png=await pngBlob();const readme=`VECTOR ME — PRINT-READY ARTWORK\n\nProject: ${basename()}\nUse case: ${state.useCase}\nMode: ${state.mode}\nPrint Check: ${state.check?.status||'Not run'}\n\nWHAT TO SEND\nT-shirt / screen printer: SVG or vector PDF\nSign / vinyl shop: SVG or vector PDF\nEmbroidery shop: SVG/PDF is preparation artwork. Your digitizer must create DST/PES machine files.\n\nVector Me automated checks do not guarantee manufacturer acceptance; vendors may have additional requirements.\n`;const zip=VectorZip.makeZip([{name:`${basename()}.svg`,data:state.svg},{name:`${basename()}-vector.pdf`,data:new Uint8Array(await pdf.arrayBuffer())},{name:`${basename()}-transparent.png`,data:new Uint8Array(await png.arrayBuffer())},{name:'README.txt',data:readme}]);downloadBlob(zip,`${basename()}-vector-me.zip`);track('download_all');}

  function resultFromSvg(svg){const doc=new DOMParser().parseFromString(svg,'image/svg+xml'),root=doc.documentElement,vb=(root.getAttribute('viewBox')||'0 0 100 100').split(/\s+/).map(Number),shapes=[];doc.querySelectorAll('path').forEach(p=>{const m=(p.getAttribute('fill')||'').match(/rgb\((\d+)\s+(\d+)\s+(\d+)\)/),nums=(p.getAttribute('d')||'').match(/-?\d+(?:\.\d+)?/g)?.map(Number)||[];if(!m||nums.length<6)return;const points=[];for(let i=0;i+1<nums.length;i+=2)points.push([nums[i],nums[i+1]]);shapes.push({color:[+m[1],+m[2],+m[3]],points,area:points.length});});return{width:vb[2]||100,height:vb[3]||100,palette:[],shapes};}
  async function saveProject(){if(!state.svg)return;if(!state.user){openAuth();els.authError.textContent='Create or sign in to save this vector.';return;}try{const data=await api('/api/projects',{method:'POST',body:JSON.stringify({name:basename(),use_case:state.useCase,mode:state.mode,svg:state.svg,print_status:state.check?.status||'READY',print_warnings:state.check?.warnings||[]})});state.loadedProjectId=String(data.project.id);els.saveProject.textContent='Saved';track('project_saved');}catch(e){alert('Could not save this project.');}}
  async function loadProjects(){if(!state.user)return;els.projectList.innerHTML='<p>Loading…</p>';els.projectsDialog.showModal();try{const {projects}=await api('/api/projects');els.projectList.innerHTML='';if(!projects.length){els.projectList.innerHTML='<p>No saved vectors yet.</p>';return;}projects.forEach(p=>{const row=document.createElement('div');row.className='project-item';row.innerHTML=`<div><strong>${escapeHtml(p.name)}</strong><p>${escapeHtml(p.use_case)} · ${escapeHtml(p.mode)} · ${new Date(p.created_at).toLocaleDateString()}</p></div><div class="project-actions"><button class="secondary" data-open="${p.id}">Open</button><button class="secondary" data-delete="${p.id}">Delete</button></div>`;els.projectList.appendChild(row);});}catch{els.projectList.innerHTML='<p>Could not load projects.</p>';}}
  async function openProject(id){const {project}=await api(`/api/projects/${encodeURIComponent(id)}`);state.file={name:project.name+'.svg'};state.image=null;state.sourceUrl=null;state.svg=project.svg;state.result=resultFromSvg(project.svg);state.mode=project.mode;state.useCase=project.use_case;state.loadedProjectId=String(project.id);state.exportUnlocked=false;state.check={status:project.print_status,warnings:project.print_warnings||[]};els.fileName.textContent=project.name;els.originalPreview.removeAttribute('src');els.vectorPreview.innerHTML=state.svg;els.compareVector.innerHTML=state.svg;els.workspace.classList.remove('hidden');els.exports.classList.remove('hidden');els.printCheck.classList.remove('hidden');els.printStatus.textContent=project.print_status;els.printWarnings.innerHTML='';(project.print_warnings?.length?project.print_warnings:['Saved project.']).forEach(w=>{const li=document.createElement('li');li.textContent=w;els.printWarnings.appendChild(li);});document.querySelectorAll('.tab[data-view="original"],.tab[data-view="compare"]').forEach(b=>b.disabled=true);setView('vector');els.projectsDialog.close();els.workspace.scrollIntoView({behavior:'smooth'});track('project_opened');}
  async function deleteProject(id){if(!confirm('Delete this saved vector? This cannot be undone.'))return;await api(`/api/projects/${encodeURIComponent(id)}`,{method:'DELETE'});track('project_deleted');loadProjects();}

  function renderUser(){const u=state.user;els.accountButton.textContent=u?u.email:'Sign in';els.projectsButton.classList.toggle('hidden',!u);els.creditBadge.classList.toggle('hidden',!u);els.creditBadge.textContent=u?`${u.credits} credits`:'';els.logoutButton.classList.toggle('hidden',!u);if(u){els.authSubmit.classList.add('hidden');els.authToggle.classList.add('hidden');els.authEmail.value=u.email;els.authEmail.disabled=true;els.authPassword.classList.add('hidden');els.authPassword.parentElement.classList.add('hidden');els.authTitle.textContent='Account';}else{els.authSubmit.classList.remove('hidden');els.authToggle.classList.remove('hidden');els.authEmail.disabled=false;els.authPassword.parentElement.classList.remove('hidden');els.authPassword.classList.remove('hidden');els.authTitle.textContent=state.authMode==='login'?'Sign in':'Create account';}}
  function openAuth(){renderUser();els.authError.textContent='';els.accountDialog.showModal();}
  async function submitAuth(){const email=els.authEmail.value.trim(),password=els.authPassword.value;els.authError.textContent='';try{const data=await api(state.authMode==='login'?'/api/auth/login':'/api/auth/register',{method:'POST',body:JSON.stringify({email,password})});state.user=data.user;renderUser();els.accountDialog.close();track(state.authMode==='login'?'login_completed':'registration_completed');}catch(e){els.authError.textContent=e.data?.error==='email_exists'?'That email already has an account.':e.data?.error==='invalid_login'?'Email or password is incorrect.':'Use a valid email and a password of at least 10 characters.';}}
  async function logout(){await api('/api/auth/logout',{method:'POST',body:'{}'});state.user=null;renderUser();els.accountDialog.close();}
  async function buyPack(pack){if(!state.user){openAuth();els.authError.textContent='Sign in or create an account before purchasing credits.';return;}try{track('checkout_started',{pack});const data=await api('/api/checkout',{method:'POST',body:JSON.stringify({pack})});location.href=data.url;}catch(e){alert(e.data?.error==='payments_not_configured'?'Payments are not configured yet. Add the Stripe environment variables to enable checkout.':'Checkout could not be started.');}}

  function reset(){if(state.sourceUrl)URL.revokeObjectURL(state.sourceUrl);state.file=null;state.image=null;state.mode='trace';state.useCase=useCases[0];state.result=null;state.svg=null;state.sourceUrl=null;state.exportUnlocked=false;state.loadedProjectId=null;state.check=null;els.fileInput.value='';els.workspace.classList.add('hidden');els.uploadError.textContent='';els.statusText.textContent='';els.analysisPanel.classList.add('hidden');document.querySelectorAll('.tab').forEach(b=>b.disabled=false);els.saveProject.textContent='Save project';initUseCases();}

  els.uploadButton.addEventListener('click',()=>els.fileInput.click());els.fileInput.addEventListener('change',e=>handleFile(e.target.files[0]));['dragenter','dragover'].forEach(ev=>els.uploadButton.addEventListener(ev,e=>{e.preventDefault();els.uploadButton.classList.add('drag');}));['dragleave','drop'].forEach(ev=>els.uploadButton.addEventListener(ev,e=>{e.preventDefault();els.uploadButton.classList.remove('drag');}));els.uploadButton.addEventListener('drop',e=>handleFile(e.dataTransfer.files[0]));
  document.querySelectorAll('.mode').forEach(b=>b.addEventListener('click',()=>{state.mode=b.dataset.mode;document.querySelectorAll('.mode').forEach(x=>x.classList.toggle('active',x===b));track(state.mode==='trace'?'trace_selected':'rebuild_selected');}));document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));els.compareSlider.addEventListener('input',()=>{els.compareVectorClip.style.clipPath=`inset(0 ${100-Number(els.compareSlider.value)}% 0 0)`;});
  els.vectorizeButton.addEventListener('click',vectorize);els.downloadSvg.addEventListener('click',downloadSvg);els.downloadPdf.addEventListener('click',downloadPdf);els.downloadPng.addEventListener('click',downloadPng);els.downloadAll.addEventListener('click',downloadAll);els.saveProject.addEventListener('click',saveProject);els.resetButton.addEventListener('click',reset);els.accountButton.addEventListener('click',openAuth);els.authSubmit.addEventListener('click',submitAuth);els.authToggle.addEventListener('click',()=>{state.authMode=state.authMode==='login'?'register':'login';renderUser();});els.logoutButton.addEventListener('click',logout);els.projectsButton.addEventListener('click',loadProjects);els.projectsClose.addEventListener('click',()=>els.projectsDialog.close());els.projectList.addEventListener('click',e=>{const open=e.target.closest('[data-open]'),del=e.target.closest('[data-delete]');if(open)openProject(open.dataset.open);if(del)deleteProject(del.dataset.delete);});document.querySelectorAll('.buy-pack').forEach(b=>b.addEventListener('click',()=>buyPack(b.dataset.pack)));
  initUseCases();api('/api/me').then(d=>{state.user=d.user;renderUser();}).catch(()=>renderUser());track('landing_page_view',{path:location.pathname});if(new URLSearchParams(location.search).get('checkout')==='success'){api('/api/me').then(d=>{state.user=d.user;renderUser();});}
})();
