(function(root,factory){const api=factory();if(typeof module!=="undefined"&&module.exports)module.exports=api;root.VectorCore=api;})(typeof globalThis!=="undefined"?globalThis:this,function(){
"use strict";
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function dist2(a,b){const dr=a[0]-b[0],dg=a[1]-b[1],db=a[2]-b[2];return dr*dr+dg*dg+db*db;}
function luminance(c){return .2126*c[0]+.7152*c[1]+.0722*c[2];}
function samplePixels(data,maxSamples=18000){const total=data.length/4,step=Math.max(1,Math.floor(total/maxSamples)),out=[];for(let i=0;i<total;i+=step){const j=i*4,a=data[j+3];if(a<16)continue;out.push([data[j],data[j+1],data[j+2]]);}return out;}
function kmeans(data,k,iterations=8){const pts=samplePixels(data);if(!pts.length)return [[0,0,0]];k=clamp(k,1,Math.min(16,pts.length));const sorted=pts.slice().sort((a,b)=>luminance(a)-luminance(b));let centers=[];for(let i=0;i<k;i++)centers.push(sorted[Math.floor((i+.5)*sorted.length/k)].slice());for(let it=0;it<iterations;it++){const sums=centers.map(()=>[0,0,0,0]);for(const p of pts){let bi=0,bd=Infinity;for(let c=0;c<centers.length;c++){const d=dist2(p,centers[c]);if(d<bd){bd=d;bi=c;}}const s=sums[bi];s[0]+=p[0];s[1]+=p[1];s[2]+=p[2];s[3]++;}centers=centers.map((c,i)=>sums[i][3]?[Math.round(sums[i][0]/sums[i][3]),Math.round(sums[i][1]/sums[i][3]),Math.round(sums[i][2]/sums[i][3])]:c);}return centers;}
function quantize(imageData,k){const centers=kmeans(imageData.data,k);const labels=new Int16Array(imageData.width*imageData.height);const alpha=new Uint8Array(labels.length);for(let i=0;i<labels.length;i++){const j=i*4,a=imageData.data[j+3];alpha[i]=a;if(a<16){labels[i]=-1;continue;}const p=[imageData.data[j],imageData.data[j+1],imageData.data[j+2]];let bi=0,bd=Infinity;for(let c=0;c<centers.length;c++){const d=dist2(p,centers[c]);if(d<bd){bd=d;bi=c;}}labels[i]=bi;}return{centers,labels,alpha};}
function likelyBackground(imageData,quant){const w=imageData.width,h=imageData.height,counts=new Map();const hit=i=>{const l=quant.labels[i];if(l>=0)counts.set(l,(counts.get(l)||0)+1);};for(let x=0;x<w;x++){hit(x);hit((h-1)*w+x);}for(let y=1;y<h-1;y++){hit(y*w);hit(y*w+w-1);}let best=-1,n=-1;for(const [k,v] of counts){if(v>n){n=v;best=k;}}return best;}
function componentsForLabel(labels,w,h,label,minArea){const seen=new Uint8Array(labels.length),comps=[];const qx=new Int32Array(labels.length),qy=new Int32Array(labels.length);for(let sy=0;sy<h;sy++)for(let sx=0;sx<w;sx++){const start=sy*w+sx;if(seen[start]||labels[start]!==label)continue;let head=0,tail=0;qx[tail]=sx;qy[tail++]=sy;seen[start]=1;const cells=[];while(head<tail){const x=qx[head],y=qy[head++],idx=y*w+x;cells.push([x,y]);if(x>0){const ni=idx-1;if(!seen[ni]&&labels[ni]===label){seen[ni]=1;qx[tail]=x-1;qy[tail++]=y;}}if(x+1<w){const ni=idx+1;if(!seen[ni]&&labels[ni]===label){seen[ni]=1;qx[tail]=x+1;qy[tail++]=y;}}if(y>0){const ni=idx-w;if(!seen[ni]&&labels[ni]===label){seen[ni]=1;qx[tail]=x;qy[tail++]=y-1;}}if(y+1<h){const ni=idx+w;if(!seen[ni]&&labels[ni]===label){seen[ni]=1;qx[tail]=x;qy[tail++]=y+1;}}}if(cells.length>=minArea)comps.push(cells);}return comps;}
const key=(x,y)=>x+","+y;
function boundaryLoops(cells){const cellSet=new Set(cells.map(c=>key(c[0],c[1]))),edges=[];for(const [x,y] of cells){if(!cellSet.has(key(x,y-1)))edges.push([[x,y],[x+1,y]]);if(!cellSet.has(key(x+1,y)))edges.push([[x+1,y],[x+1,y+1]]);if(!cellSet.has(key(x,y+1)))edges.push([[x+1,y+1],[x,y+1]]);if(!cellSet.has(key(x-1,y)))edges.push([[x,y+1],[x,y]]);}const starts=new Map();edges.forEach((e,i)=>{const k=key(e[0][0],e[0][1]);if(!starts.has(k))starts.set(k,[]);starts.get(k).push(i);});const used=new Uint8Array(edges.length),loops=[];for(let i=0;i<edges.length;i++){if(used[i])continue;let idx=i,loop=[],guard=0;while(!used[idx]&&guard++<edges.length+5){used[idx]=1;const e=edges[idx];loop.push(e[0]);const end=e[1],cand=starts.get(key(end[0],end[1]))||[];const next=cand.find(j=>!used[j]);if(next===undefined){loop.push(end);break;}idx=next;if(idx===i)break;}if(loop.length>=4)loops.push(loop);}return loops;}
function perpendicularDistance(p,a,b){const dx=b[0]-a[0],dy=b[1]-a[1];if(dx===0&&dy===0)return Math.hypot(p[0]-a[0],p[1]-a[1]);const t=((p[0]-a[0])*dx+(p[1]-a[1])*dy)/(dx*dx+dy*dy);const x=a[0]+t*dx,y=a[1]+t*dy;return Math.hypot(p[0]-x,p[1]-y);}
function rdp(points,epsilon){if(points.length<3)return points;let dmax=0,index=0;for(let i=1;i<points.length-1;i++){const d=perpendicularDistance(points[i],points[0],points[points.length-1]);if(d>dmax){index=i;dmax=d;}}if(dmax>epsilon){const a=rdp(points.slice(0,index+1),epsilon),b=rdp(points.slice(index),epsilon);return a.slice(0,-1).concat(b);}return[points[0],points[points.length-1]];}
function simplifyClosed(loop,epsilon){if(loop.length<6)return loop;const open=loop.concat([loop[0]]);const simp=rdp(open,epsilon);if(simp.length>2&&simp[simp.length-1][0]===simp[0][0]&&simp[simp.length-1][1]===simp[0][1])simp.pop();return simp;}
function rgb(c){return`rgb(${c[0]} ${c[1]} ${c[2]})`;}
function vectorize(imageData,options={}){const w=imageData.width,h=imageData.height,colorCount=options.colorCount||4,quant=quantize(imageData,colorCount),bg=options.removeBackground?likelyBackground(imageData,quant):-1;const detail=options.detail||"medium",minArea=detail==="high"?2:detail==="low"?Math.max(8,Math.round(w*h*.00015)):Math.max(4,Math.round(w*h*.00006));const epsilon=options.mode==="rebuild"?(detail==="high"?.8:detail==="low"?2.8:1.7):(detail==="high"?.35:detail==="low"?1.5:.85);const shapes=[];for(let label=0;label<quant.centers.length;label++){if(label===bg)continue;const comps=componentsForLabel(quant.labels,w,h,label,minArea);for(const cells of comps){for(const loop of boundaryLoops(cells)){const pts=simplifyClosed(loop,epsilon);if(pts.length<3)continue;shapes.push({color:quant.centers[label],points:pts,area:cells.length});}}}shapes.sort((a,b)=>b.area-a.area);return{width:w,height:h,palette:quant.centers,backgroundLabel:bg,shapes};}
function resultToSvg(result){const paths=result.shapes.map(s=>`<path fill="${rgb(s.color)}" d="M ${s.points.map((p,i)=>`${p[0]} ${p[1]}${i<s.points.length-1?" L ":""}`).join("")} Z"/>`).join("");return`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${result.width} ${result.height}" width="${result.width}" height="${result.height}" role="img" aria-label="Vectorized artwork">${paths}</svg>`;}
function pdfEscape(n){return Number(n.toFixed(2));}
function resultToPdf(result){const W=612,H=612*result.height/result.width,scale=612/result.width;let stream="q\n1 0 0 -1 0 "+pdfEscape(H)+" cm\n";for(const s of result.shapes){const c=s.color;stream+=`${(c[0]/255).toFixed(4)} ${(c[1]/255).toFixed(4)} ${(c[2]/255).toFixed(4)} rg\n`;s.points.forEach((p,i)=>{stream+=`${pdfEscape(p[0]*scale)} ${pdfEscape(p[1]*scale)} ${i?"l":"m"}\n`;});stream+="h f\n";}stream+="Q\n";const objects=[];objects[1]="<< /Type /Catalog /Pages 2 0 R >>";objects[2]="<< /Type /Pages /Kids [3 0 R] /Count 1 >>";objects[3]=`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 ${pdfEscape(H)}] /Contents 4 0 R /Resources << >> >>`;objects[4]=`<< /Length ${stream.length} >>\nstream\n${stream}endstream`;let pdf="%PDF-1.4\n",offsets=[0];for(let i=1;i<=4;i++){offsets[i]=pdf.length;pdf+=`${i} 0 obj\n${objects[i]}\nendobj\n`;}const xref=pdf.length;pdf+="xref\n0 5\n0000000000 65535 f \n";for(let i=1;i<=4;i++)pdf+=String(offsets[i]).padStart(10,"0")+" 00000 n \n";pdf+=`trailer\n<< /Size 5 /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;return new Blob([pdf],{type:"application/pdf"});}
function printCheck(result,useCase){const warnings=[];const nodeCount=result.shapes.reduce((n,s)=>n+s.points.length,0),tiny=result.shapes.filter(s=>s.area<20).length;if(!result.shapes.length)warnings.push("No usable vector shapes were detected.");if(nodeCount>12000)warnings.push("The artwork has a very high node count; some production software may process it slowly.");if(tiny>30)warnings.push(`${tiny} very small shapes may disappear in production.`);if(result.palette.length>8&&(useCase==="Screen printing"||useCase==="Hat / embroidery"))warnings.push("This artwork uses many colors for the selected production method.");if(useCase==="Hat / embroidery")warnings.push("This vector is preparation artwork only. An embroidery digitizer must still create DST/PES machine files.");return{status:warnings.length?"NEEDS ATTENTION":"READY",warnings,nodeCount,tinyShapes:tiny};}
return{vectorize,resultToSvg,resultToPdf,printCheck,quantize,likelyBackground,simplifyClosed};
});
